### PR TITLE
Signup HTML form

### PR DESCRIPTION
**Pull request by kagaramag**
## Title
Signup HTML form

### CODE REVIEW

**Comment by euqueme** [comment]
## Pull Request under the review by Maria Eugenia Quemé P. (TSE)

**Comment by euqueme** [comment]
> ## Pull Request under the review by Maria Eugenia Quemé P. (TSE)

## Hello @djallas  and @Genius8  :woman_technologist:
## This is a great effort :muscle: the page looks almost like the original :art:  but there are still a few Mandatory changes to work on before we can give you the approval:

- [ ] Change **Sign In** form title to **Create an Intuit account** ([link to page](https://accounts.intuit.com/signup.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Ftask%3DS))

- [ ] Don't use **div** and **span** tags since these are non-semantic elements as stated in the [Additional Microverse Requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/)  in the section (Remember to use semantic HTML.)

- [ ] Validate your HTML markup with a validator (as described in the [Additional Microverse Requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/)).

[Suggestion] Use the nav tag for major navigation links (in this case the top-right of the page)
[Suggestion] Use the main tag for the dominant content of the body (the form)

Also, I noticed you used different feature branches, for this project scope you only need one feature branch, take this into account for future projects.

## That's it. Please :pray: correct these changes and submit back for a code review when you are done :rocket:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Congratulations @djallas and @euqueme 
This is a really beautiful project. Please attend to the change I am proposing below and submit for a re-review once you're done! See you at the top :rocket: 

#### HTML Validation
Please condsider parsing your HTML markup through this validator and correct all resulting errors. It is mandatory that your markup is free from semantic or syntax errors.
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — APPROVED** [review]
# Congrats team!
You may merge and keep moving on! See you at the very top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by euqueme** [comment]
> # Congrats team!
> You may merge and keep moving on! See you at the very top 
> 
> ##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

## Way to go! @Genius8 and @djallas :tada:

**Pull request merged**
